import type { EmployerJobsPosted } from "../types";

export const employerJobsPostedMock: EmployerJobsPosted[] = [
  {
    id: "9b6f8c42-3f2e-4e7b-bdd1-7a9f0d6c9a21",
    position: "Frontend Developer",
    location: "Remote",
    postedDate: "2025-11-02",
    employmentType: "Full-time",
    isOpen: true,
    noOfApplicants: 34,
  },
  {
    id: "1c4a2e9b-8d7f-4a21-9a52-9c71bce03c8d",
    position: "Backend Engineer",
    location: "Amsterdam, NL",
    postedDate: "2025-10-28",
    employmentType: "Full-time",
    isOpen: true,
    noOfApplicants: 21,
  },
  {
    id: "5e8a71d2-4b9f-4d60-a9c1-2f7a0e4d8c53",
    position: "UI/UX Designer",
    location: "Berlin, DE",
    postedDate: "2025-10-20",
    employmentType: "Contract",
    isOpen: false,
    noOfApplicants: 47,
  },
  {
    id: "7a2f6e4b-91c3-4a8d-bf70-4e29c8d12a6f",
    position: "Product Manager",
    location: "London, UK",
    postedDate: "2025-10-15",
    employmentType: "Full-time",
    isOpen: true,
    noOfApplicants: 18,
  },
  {
    id: "e4b6a7c9-3d2f-4a91-8f62-0a9d4c1e5b77",
    position: "QA Engineer",
    location: "Remote",
    postedDate: "2025-10-10",
    employmentType: "Part-time",
    isOpen: false,
    noOfApplicants: 29,
  },
  {
    id: "c2d9f61a-8b73-4c4f-9e15-71d8f0a4e926",
    position: "DevOps Engineer",
    location: "Dublin, IE",
    postedDate: "2025-10-05",
    employmentType: "Contract",
    isOpen: true,
    noOfApplicants: 12,
  },
  {
    id: "0f9d6b1a-6a4c-4e0a-bc21-85d2a3f9e412",
    position: "Mobile App Developer",
    location: "Toronto, CA",
    postedDate: "2025-09-30",
    employmentType: "Full-time",
    isOpen: true,
    noOfApplicants: 26,
  },
  {
    id: "b1e8a7d3-2c6f-49b7-a4f1-90d2e7c63a8b",
    position: "Data Analyst",
    location: "Paris, FR",
    postedDate: "2025-09-25",
    employmentType: "Part-time",
    isOpen: false,
    noOfApplicants: 41,
  },
  {
    id: "6a4c8e9b-0f3d-4e2c-9b6d-2c7f1a8d5e90",
    position: "Technical Writer",
    location: "Remote",
    postedDate: "2025-09-20",
    employmentType: "Contract",
    isOpen: true,
    noOfApplicants: 9,
  },
  {
    id: "8d2f4c9a-7b6e-4d0f-91a5-3c8e2a9f6b71",
    position: "Customer Support Engineer",
    location: "Madrid, ES",
    postedDate: "2025-09-15",
    employmentType: "Full-time",
    isOpen: false,
    noOfApplicants: 33,
  },
];

export const inputFields = [
  {
    type: "input",
    name: "jobTitle",
    label: "Job Title",
    placeholder: "e.g Senior Frontend Engineer",
    inputType: "text",
  },
  {
    type: "input",
    name: "location",
    label: "Location",
    placeholder: "e.g San Francisco, CA",
    inputType: "text",
  },
  {
    type: "input",
    name: "minSalary",
    label: "Minimum Salary (USD - $)",
    placeholder: "e.g 10000",
    inputType: "number",
  },
  {
    type: "input",
    name: "maxSalary",
    label: "Maximum Salary (USD - $)",
    placeholder: "e.g 150000",
    inputType: "number",
  },
  {
    type: "select",
    name: "jobType",
    label: "Employment Type",
    options: [
      { label: "Full-time", value: "full-time" },
      { label: "Part-time", value: "part-time" },
      { label: "Contract", value: "contract" },
    ],
  },
  {
    type: "input",
    name: "jobDesc",
    label: "Job Description",
    placeholder:
      "Describe the role, responsibilities, and what you're looking for...",
    inputType: "text",
  },
  {
    type: "input",
    name: "requirement",
    label: "Requirements",
    placeholder:
      "List the qualifications, skills, and experience needed...",
    inputType: "text",
  },
];

